### PR TITLE
prefer /dev/papr-vpd and /dev/papr-sysparm when available

### PR DESCRIPTION
**Pull request by nathanlynch**
Latest draft of support for proposed character device APIs for VPD and system parameters.

This is a draft PR and will likely need updates according to how the kernel submission goes.

Link to kernel submission:
https://lore.kernel.org/linuxppc-dev/20231006-papr-sys_rtas-vs-lockdown-v1-0-3a36bfb66e2e@linux.ibm.com/T/#m53331fa7cc95245a94d4ab5a288be21305eb5053

### CODE REVIEW

**Comment by nathanlynch** [comment]
Link to v3 kernel submission https://lore.kernel.org/linuxppc-dev/20231025-papr-sys_rtas-vs-lockdown-v3-0-5eb04559e7d8@linux.ibm.com/

**Comment by hramrach** [comment]
That pthread_once indeed breaks libservicelog build:

```
[   78s] configure:17257: gcc -o conftest -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g   conftest.c -lrtas  -lrtasevent -lsqlite3  >&5
[   78s] /usr/lib64/gcc/powerpc64le-suse-linux/7/../../../../powerpc64le-suse-linux/bin/ld: /usr/lib64/gcc/powerpc64le-suse-linux/7/../../../../lib64/librtas.so: undefined reference to `pthread_once'
[   78s] collect2: error: ld returned 1 exit status
```

**Comment by hramrach** [comment]
```
--- librtas-2.0.5.orig/Makefile.am
+++ librtas-2.0.5/Makefile.am
@@ -26,7 +26,7 @@
 LIBRTAS_LIBRARY_VERSION = $(LIBRTAS_CURRENT):$(LIBRTAS_REVISION):$(LIBRTAS_AGE)
 
 lib_LTLIBRARIES += librtas.la
-librtas_la_LDFLAGS = -version-info $(LIBRTAS_LIBRARY_VERSION)
+librtas_la_LDFLAGS = -version-info $(LIBRTAS_LIBRARY_VERSION) -lpthread
 librtas_la_SOURCES = \
 	librtas_src/vpd.c \
 	librtas_src/ofdt.c \

```

**Comment by hramrach** [comment]
Kernel submission is merged.

**Comment by nathanlynch** [comment]
@tyreld please add to the next branch, assuming you see no issues. The kernel components are now upstream and queued for 6.8.

Since this code introduces the first use of a pthread API in librtas, I've added `-lpthread` to the link step (thanks @hramrach).

**Comment by tyreld** [comment]
Thanks for the update. Still catching up from the holiday, but I will get this queued soon.

**Comment by tyreld** [comment]
Merged the following commits

https://github.com/ibm-power-utilities/librtas/commit/d8d4ee6f5052704ac82bb8aa8d8fe8816dac41cd
https://github.com/ibm-power-utilities/librtas/commit/57d5e1c07b40e56f6209e7b806208818464f8e8d
https://github.com/ibm-power-utilities/librtas/commit/c914a1a701391c565203b10603ad0fbc52438bf7
https://github.com/ibm-power-utilities/librtas/commit/c47176a5f1ce7bb16ba02b8c8520e02b285d7e9f
https://github.com/ibm-power-utilities/librtas/commit/ee06898b1e7807a6e201b281ffc8ee3fa96136f4
https://github.com/ibm-power-utilities/librtas/commit/569da8e5f0d5009694dc2def350cb9cd2c1d81a6
https://github.com/ibm-power-utilities/librtas/commit/0ca359b34221465dac6999ad957a41ac4f5edc92
https://github.com/ibm-power-utilities/librtas/commit/4c44465e6d54acdd31ac28334441468375496e4f

**Pull request closed without merging**
