### PR TITLE
validate externally visible symbols

### PR DESCRIPTION
**Pull request by nathanlynch**
Add a test that validates visible symbols in the built shared libraries. This will help keep us honest when it comes to maintaining the ABI.

The test script can be used to regenerate the symbol lists automatically, see the commit message for "add symbol visibility test".

Example failed run:
https://github.com/nathanlynch/librtas/actions/runs/2072297597

### CODE REVIEW

**Comment by tyreld** [comment]
I think we should collect test-suite.log on failure. Something like the following after running check should work:

```    
- name: Collect test-suite.log
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: test-suite.log
        path: ./test-suite.log```

**Comment by nathanlynch** [comment]
> I think we should collect test-suite.log on failure. 

Ah, thanks for catching this. Looking at my example failed run I can see the outputs have already disappeared. I will do as you suggest.

**Comment by nathanlynch** [comment]
> > I think we should collect test-suite.log on failure.
> 
> Ah, thanks for catching this. Looking at my example failed run I can see the outputs have already disappeared.

I was mistaken here. I happened to look at the log while not logged in, which confusingly gives:

> Error: The log was not found. It may have been deleted based on retention settings.

But it's still there if I look at it while logged in.

The tests are run with `VERBOSE=1`, so test-suite.log is output on failure, as can be seen in the example.

@tyreld did you suggest this so we can retain the test log beyond the default retention period?

**Comment by tyreld** [comment]
> > > I think we should collect test-suite.log on failure.
> > 
> > 
> > Ah, thanks for catching this. Looking at my example failed run I can see the outputs have already disappeared.
> 
> I was mistaken here. I happened to look at the log while not logged in, which confusingly gives:
> 
> > Error: The log was not found. It may have been deleted based on retention settings.
> 
> But it's still there if I look at it while logged in.
> 
> The tests are run with `VERBOSE=1`, so test-suite.log is output on failure, as can be seen in the example.
> 
> @tyreld did you suggest this so we can retain the test log beyond the default retention period?

No, because I think artifact retention is the same as the console log. I think with `VERBOSE=1` the console capture has plenty of info. So, I'm inclined to agree now that collecting `test-suite.log` is overkill.

**Comment by nathanlynch** [comment]
Been working with https://lvc.github.io/abi-compliance-checker/ . This is what glibc and other projects use, and it's much more robust than what I have here.

**Comment by tyreld** [comment]
> Been working with https://lvc.github.io/abi-compliance-checker/ . This is what glibc and other projects use, and it's much more robust than what I have here.

I noticed your comment in Jira about the ABI checker. So, do I pickup what you proposed here for the time being, or will you have something that uses the abi-compliance-checker soon?

**Comment by nathanlynch** [comment]
> I noticed your comment in Jira about the ABI checker. So, do I pickup what you proposed here for the time being, or will you have something that uses the abi-compliance-checker soon?

I've got a lot of the work done to make the compliance checker work, but it's more involved. Hope to have a new PR this week. If that work gets preempted or something then we can fall back to what I have here, but I'm not anxious to have it pulled right now.

**Comment by tyreld** [comment]
Ok, lets put this one on the back burner for the time being.

**Comment by nathanlynch** [comment]
withdrawing this in favor of #24

**Pull request closed without merging**
