### PR TITLE
librtasevent: Fix memory page address print issue

### PR DESCRIPTION
**Pull request by hegdevasant**
Signed-off-by: Vasant Hegde <hegdevasant@linux.vnet.ibm.com>

### CODE REVIEW

**Review by nathanlynch — COMMENTED** [review]
Why is it correct to swap the order? (Write a commit message please)

**Comment by nathanlynch** [comment]
thanks - it's still not clear to me why swapping the order is right. It's unintuitive to me at least that the low order half should precede the higher order. Are the fields misnamed?

**Comment by hegdevasant** [comment]
> thanks - it's still not clear to me why swapping the order is right. It's unintuitive to me at least that the low order half should precede the higher order. Are the fields misnamed?

Yes. I think its misnamed.

-Vasant

**Comment by nathanlynch** [comment]
> >  Are the fields misnamed?
> 
> Yes. I think its misnamed.

OK. Can the fields be renamed?

**Comment by hegdevasant** [comment]
@nathanlynch done. I have updated structures.

-Vasant

**Comment by nathanlynch** [comment]
thanks @hegdevasant, what I should have said is "is it OK to rename the fields"? I hesitate because these structures appear to be in a public header.

**Comment by nathanlynch** [comment]
Also, "Platform Event Log Format, Logical Resource Identification section" in PAPR makes the current naming make more sense, I think?

`lri_mem_addr_lo` == Memory Logical Address (bit 0-31), for resource type = memory page
`lri_mem_addr_hi` == Memory Logical Address (bit 32-64)), for resource type = memory page

that is, the "lo" and "hi" refer to the bit numbering and not significance.
https://en.wikipedia.org/wiki/Bit_numbering

**Comment by tyreld** [comment]
Fixed by commit https://github.com/ibm-power-utilities/librtas/commit/9e94372d1f82ad694c5e51ff9f75f3b35b6aa114

**Comment by tyreld** [comment]
Based on @nathanlynch comment about the naming being correct before I've instead committed the first iteration of the patch that simply swaps the order that the addr_[lo|hi] fields are printed.

f8a1f6df2526

**Pull request closed without merging**
